#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BlackJack")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertTable(Table instance);
  partial void UpdateTable(Table instance);
  partial void DeleteTable(Table instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BlackJackConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Table> Tables
	{
		get
		{
			return this.GetTable<Table>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Table]")]
public partial class Table : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _isimsoyisim;
	
	private string _kartnumarasi;
	
	private string _bitistarihiay;
	
	private string _bitistarihiyil;
	
	private string _urunismi;
	
	private int _fiyat;
	
	private string _kartarkanumarasi;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnisimsoyisimChanging(string value);
    partial void OnisimsoyisimChanged();
    partial void OnkartnumarasiChanging(string value);
    partial void OnkartnumarasiChanged();
    partial void OnbitistarihiayChanging(string value);
    partial void OnbitistarihiayChanged();
    partial void OnbitistarihiyilChanging(string value);
    partial void OnbitistarihiyilChanged();
    partial void OnurunismiChanging(string value);
    partial void OnurunismiChanged();
    partial void OnfiyatChanging(int value);
    partial void OnfiyatChanged();
    partial void OnkartarkanumarasiChanging(string value);
    partial void OnkartarkanumarasiChanged();
    #endregion
	
	public Table()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isimsoyisim", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string isimsoyisim
	{
		get
		{
			return this._isimsoyisim;
		}
		set
		{
			if ((this._isimsoyisim != value))
			{
				this.OnisimsoyisimChanging(value);
				this.SendPropertyChanging();
				this._isimsoyisim = value;
				this.SendPropertyChanged("isimsoyisim");
				this.OnisimsoyisimChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kartnumarasi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string kartnumarasi
	{
		get
		{
			return this._kartnumarasi;
		}
		set
		{
			if ((this._kartnumarasi != value))
			{
				this.OnkartnumarasiChanging(value);
				this.SendPropertyChanging();
				this._kartnumarasi = value;
				this.SendPropertyChanged("kartnumarasi");
				this.OnkartnumarasiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bitistarihiay", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string bitistarihiay
	{
		get
		{
			return this._bitistarihiay;
		}
		set
		{
			if ((this._bitistarihiay != value))
			{
				this.OnbitistarihiayChanging(value);
				this.SendPropertyChanging();
				this._bitistarihiay = value;
				this.SendPropertyChanged("bitistarihiay");
				this.OnbitistarihiayChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bitistarihiyil", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string bitistarihiyil
	{
		get
		{
			return this._bitistarihiyil;
		}
		set
		{
			if ((this._bitistarihiyil != value))
			{
				this.OnbitistarihiyilChanging(value);
				this.SendPropertyChanging();
				this._bitistarihiyil = value;
				this.SendPropertyChanged("bitistarihiyil");
				this.OnbitistarihiyilChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_urunismi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string urunismi
	{
		get
		{
			return this._urunismi;
		}
		set
		{
			if ((this._urunismi != value))
			{
				this.OnurunismiChanging(value);
				this.SendPropertyChanging();
				this._urunismi = value;
				this.SendPropertyChanged("urunismi");
				this.OnurunismiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fiyat", DbType="Int NOT NULL")]
	public int fiyat
	{
		get
		{
			return this._fiyat;
		}
		set
		{
			if ((this._fiyat != value))
			{
				this.OnfiyatChanging(value);
				this.SendPropertyChanging();
				this._fiyat = value;
				this.SendPropertyChanged("fiyat");
				this.OnfiyatChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kartarkanumarasi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string kartarkanumarasi
	{
		get
		{
			return this._kartarkanumarasi;
		}
		set
		{
			if ((this._kartarkanumarasi != value))
			{
				this.OnkartarkanumarasiChanging(value);
				this.SendPropertyChanging();
				this._kartarkanumarasi = value;
				this.SendPropertyChanged("kartarkanumarasi");
				this.OnkartarkanumarasiChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
